### ISSUE TITLE
 SSB pub test data -- blobs

### ISSUE THREAD

**Issue by rabble** [planetary-social/planetary-pub#3]
As a developer, I want to see the sample posts from the JSON file, so I can start implementing the Preact components along with their CSS customization

Here's the URL to the JSON file -- https://github.com/planetary-social/planetary-ios/blob/master/Resources/Preload.bundle/Feeds/consolidatedFeed.json

We should either have a script that populates the DB with data, or have the server follow another ssb pub so that it replicates data

`sbot` is in a local process. You could make an idempotent function that writes to the DB when it starts iff there is not already things in the DB.

* [x] need to be able to run a script that will write to the DB. Do it as an idempotent operation on server start
  - [x] post some threaded messages
  - [x] post some picture-only messages
    + depends on blob storage. Don't think about UI in this issue; we can just call the `blobs.add` method and then call the `publish` method later. I suppose the text content should include the blob CID
  - [ ] post several messages with the same hash tag
  - [x] multiple messages by the same user

**Comment by nichoth** [comment]
Depends on https://github.com/planetary-social/viewer-frontend/issues/1
